import { app, BrowserWindow, ipcMain } from 'electron';
import { getLlamaInstallStatus, installLatestLlama, LlamaSetupProgress } from './llamaSetup';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = async (): Promise<void> => {
  const status = await getLlamaInstallStatus();

  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // Initial route state decided by install status; renderer uses this to show setup screen when needed.
  const startupParams = new URLSearchParams();
  startupParams.set('llamaInstalled', status.installed ? '1' : '0');
  if (status.version) startupParams.set('llamaVersion', status.version);

  // and load the index.html of the app with query params.
  mainWindow.loadURL(`${MAIN_WINDOW_WEBPACK_ENTRY}?${startupParams.toString()}`);

  // Open the DevTools (optional; comment out in production).
  mainWindow.webContents.openDevTools();
};

// IPC wiring for llama.cpp setup (main & preload will use these channels).
ipcMain.handle('llama-get-status', async () => {
  return getLlamaInstallStatus();
});

ipcMain.handle('llama-install-latest', async (event) => {
  const webContents = event.sender;

  const progressCallback = (p: LlamaSetupProgress) => {
    webContents.send('llama-install-progress', p);
  };

  return installLatestLlama(progressCallback);
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
